# Main config file for icon theme.
theme = "hugo-icon"
baseURL = "http://compe.malainey.com/"
languageCode = "en-CA"
title = "Computer Engineering Club"

# Metadata
[params]
  author = "Curtis Malainey"
  description = ""

# Hero section (from here on is for icon theme)
[params.hero]
  img = "img/blurred-hardware.jpg"
  title = "Computer Engineering Club"
  description = "Hardware, Software, and everything in between!"

# Navigation section
[params.nav]
  mission = "Announcements"
  services = "About Us"
  team = "The Team"
  contact = "Get In Touch"
  # Include logo instead if HOME:
  # logo = "img/logo-white-small.png"

# Mission section
[params.mission]
  enable = true

  [params.mission.images]
    enable = true

    [[params.mission.images.list]]
      img = "img/jerseys.jpg"
    [[params.mission.images.list]]
      img = "img/hackED2018.jpg"
    [[params.mission.images.list]]
      img = "img/hoodies.jpg"
    [[params.mission.images.list]]
      img = "img/hackED2017.jpg"

  [[params.mission.item]]
    weight = 1
    name = "elections"
    title = "2018-2019 Elections"
    subtitle = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ratione voluptate laborum sapiente officiis molestiaea."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae aliquid aperiam eveniet officia molestiae temporibus beatae dolores dignissimos aspernatur eius doloremque ad, eaque pariatur, repellendus illum, nostrum velit necessitatibus molestias.</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 2
    name = "mace"
    title = "MACE"
    subtitle = "Meet A Computer Engineer Night"
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae aliquid aperiam eveniet officia molestiae temporibus beatae dolores dignissimos aspernatur eius doloremque ad, eaque pariatur, repellendus illum, nostrum velit necessitatibus molestias.</p><ul class='checked'><li>Web Development</li><li>User Interface Experts</li><li>Pixel Perfect Design</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

  [[params.mission.item]]
    weight = 3
    name = "fyn"
    title = "First Year Night"
    subtitle = "Quam quasi illum expedita dicta nemo fugit reprehenderit similique! Corporis praesentium magnam sequi."
    description = "<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla explicabo, molestiae eaque fugiat dolores est esse, doloremque placeat assumenda corrupti officia dolorum. Sunt saepe ut, explicabo consectetur, nostrum illo est.</p><ul class='checked'><li>Free HTML5 Templates</li><li>Free Bootstrap Templates</li><li>Free HTML5 Bootstrap Templates</li></ul><p><a href='#' class='btn btn-primary btn-outline fh5co-content-nav' data-nav-section='contact'>Get In Touch</a></p>"

# Services section
[params.services]
  enable = true
  video = true
  # vidlink = "https://vimeo.com/channels/staffpicks/93951774"
  title = "About Us"
  description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-star"
    title = "Events"
    description = "We organize events for the Computer Engineering Club student body such as hackathons, a Geer Week team, and HackTime."

  [[params.services.item]]
    icon = "icon-eye"
    title = "Retina Ready"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-paper-plane"
    title = "Light Speed"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-pencil"
    title = "Copyrighting"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-rocket"
    title = "Load Fast"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

  [[params.services.item]]
    icon = "icon-support"
    title = "Customer Support"
    description = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Work section
[params.work]
  enable = true

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "img/gc_controller.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_2.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_3.jpg"

  [[params.work.item]]
    title = "Consectetur adipisicing"
    subtitle = "Web Design"
    img = "images/img_4.jpg"

# Team section
[params.team]
  enable = true
  title = "The Execs"
  description = "Welcome to the Computer Engineering club! <br/>Our group is a fantastic way to network with other engineering students and to hang out with some terrific and terrifying people. Below is a list of all the formal executives with the Computer Engineering club. However, there are many more contributing members. If you are interested in working with the Computer Engineering club, come hang out in our club room in ETLC or attend some of our events."

  [[params.team.item]]
    name = "Jessica Prieto"
    position = "President"
    description = "5th Year"
    img = "img/JessicaP.png"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Curtis Malainey"
    position = "Co-VP External"
    description = "5th Year Software Co-op"
    img = "img/CurtisM.png"
    github = "https://github.com/cujomalainey"
    linkedin = "https://www.linkedin.com/in/curtis-malainey-2569a38a/"

  [[params.team.item]]
    name = "George Antonious"
    position = "Co-VP External"
    description = "5th Year Software Co-op"
    img = "img/GeorgeA.png"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Petar Cvijovic"
    position = "VP Internal (Fall)"
    description = "4th Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Derek Shultz"
    position = "VP Internal (Winter)"
    description = "5th Year Software Co-op"
    img = "img/DerekS.png"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Shally Banh"
    position = "VP Social (Fall)"
    description = "4th Year Software Co-op"
    img = "img/ShallyB.png"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Ryan Huard"
    position = "VP Social (Winter)"
    description = "5th Year Nano Co-op"
    img = "img/RyanH.png"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Ishaat Chowdhury"
    position = "VP Finance (Fall)"
    description = "4th Year Software Co-op"
    img = "img/IshaatC.png"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Nathan Doraty"
    position = "VP Finance (Winter)"
    description = "4th Year Co-op"
    img = "img/NathanD.png"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Ahmed El Gohary"
    position = "2nd Year Rep"
    description = "2nd Year Software"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Paul Solleza"
    position = "3rd Year Rep"
    description = "3rd Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "William Nichols"
    position = "4th Year Rep"
    description = "4th Year"
    img = "img/WilliamN.png"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Steven Boddez"
    position = "5th Year Rep"
    description = "5th Year Software"
    img = "img/StevenB.png"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Amir Shukhayev"
    position = "Co-op Rep"
    description = "Nth Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Raymond Sarinas"
    position = "Office Rep"
    description = "Nth Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Navras Kamal"
    position = "Marketing Rep"
    description = "Nth Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Danish Dua"
    position = "Merch Rep"
    description = "Nth Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Christian Lo"
    position = "Merch Rep"
    description = "Nth Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Gaurav Sekhar"
    position = "PR Rep"
    description = "Nth Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Erik Lewis"
    position = "Geer Week Rep"
    description = "Nth Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Jessica Dâ€™Cunha"
    position = "Stock Rep"
    description = "Nth Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Jordan Los"
    position = "Stock Rep"
    description = "Nth Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

  [[params.team.item]]
    name = "Cole Milburn"
    position = "Stock Rep"
    description = "Nth Year"
    img = "images/person3.jpg"
    # facebook = "#"
    # twitter = "#"
    # dribbble = "#"
    # instagram = "#"
    github = "#"
    # linkedin = "#"

# Contact section
[params.contact]
  enable = true
  title = "Get In Touch"
  message = "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet nam itaque ipsam iste provident quo ipsam iste provident."

# Footer section
# Note here that the copyright and attribution statement must remain as part of the license agreement. If you wish to remove this, please contact freehtml5 and pay for a professional license.
[params.footer]
  enable = true
  note = "<p><small>&copy; 2016 Free HTML5 Template. All Rights Reserved. <br> Designed by <a href='http://freehtml5.co/' target='_blank'>FreeHTML5.co</a> Demo Images: <a href='http://pexels.com/' target='_blank'>Pexels</a><br>Hugo port by <a href='https://github.com/SteveLane/' target='_blank'>SteveLane</a></small></p>"
  github = "#"
  twitter = "#"
  facebook = "#"
  vine = "#"
  linkedin = "#"
  instagram = "#"

